[package]
name = "1brc"
version = "0.1.0"
edition = "2021"

[dependencies]
fast-float = "0.2.0"
lazy_static = "1.4.0"
memmap = "0.7.0"
rayon = "1.9.0"
rustc-hash = "1.1.0"

[profile.release]
debug = 1
